import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarContextProvider } from "@/context/SideBarContext";
import SideBar from "@/components/sidebar/SideBar";
import AppBar from "@/components/appbar/AppBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarContextProvider>
          <div className="flex">
            <SideBar />
            <AppBar />
          </div>

          <main>{children}</main>
        </SidebarContextProvider>
      </body>
    </html>
  );
}
